version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
